### PR TITLE
Add bats tests

### PR DESCRIPTION
**Pull request by msabramo**
```
$ bats tests/tests.bats
...
 ✓ 'vault ' => commands
 ✓ 'vault c' => commands
 ✓ 'vault p' => commands
 ✓ 'vault r' => commands
 ✓ 'vault read' => cubbyhole/ secret/ sys/
 ✓ 'vault read c' => cubbyhole/
 ✓ 'vault read s' => secret/ sys/
 ✓ 'vault list' => cubbyhole/ secret/ sys/
 ✓ 'vault list c' => cubbyhole/
 ✓ 'vault list s' => secret/ sys/
 ✓ 'vault list cubbyhole/' => cubbyhole/test

11 tests, 0 failures
```

### CODE REVIEW

**Comment by iljaweis** [comment]
Tried and failed to get the tests to run.

First, it's not obvious that a vault server needs to be running at http://127.0.0.1:8200. And the tests inherit the environment from where you're running them. Perhaps it's possible to use setup for that?

Second, the first tests fails for me:

    $ bats tests
     ✗ 'vault ' => commands
       (from function `fail' in file tests/tests.bats, line 11,
        in test file tests/tests.bats, line 18)
         `[[ "$output" =~ 'audit-disable audit-enable' ]] || fail "output was: \"$output\""' failed
       output was: "vault-bash-completion.sh: line 24: COMP_WORDS: bad array subscript"
     ✓ 'vault c' => commands
     ✓ 'vault p' => commands
     ✓ 'vault r' => commands
     ✓ 'vault read' => cubbyhole/ secret/ sys/
     ✓ 'vault read c' => cubbyhole/
     ✓ 'vault read s' => secret/ sys/
     ✓ 'vault list' => cubbyhole/ secret/ sys/
     ✓ 'vault list c' => cubbyhole/
     ✓ 'vault list s' => secret/ sys/
     ✓ 'vault list cubbyhole/' => cubbyhole/test


I have added some debugging output; the relevant values are:

    COMP_WORDS=vault size=1 COMP_CWORD=0

The problem seems to be that this does not work:

    $ get_completions 'vault '
    -bash: COMP_WORDS: bad array subscript

with debug output:

    $ get_completions 'vault '
     COMP_WORDS=vault prev= line=vault

**Comment by msabramo** [comment]
That's a good idea to have the tests set up the environment so it doesn't depend on a vault server being running and such. In fact, I started playing around a bit with running the Vault server in a Docker container. I'll send a PR if I get that working...

Re: the error - thanks! At first, I couldn't reproduce it, but I think that's because:

```
marca@marca-mac2:~/dev/git-repos/vault-bash-completion$ /usr/local/bin/bash --version | head -n 1
GNU bash, version 4.4.5(1)-release (x86_64-apple-darwin14.5.0)
```

but I was able to reproduce after noticing that my `/bin/bash` is `3.2.57(1)` and then messing with the `PATH` to make sure that the older version of `bash` gets picked up:

```
marca@marca-mac2:~/dev/git-repos/vault-bash-completion$ PATH=/bin:/usr/local/bin:/usr/bin bats tests/tests.bats
Running "bats-exec-test" on "/Users/marca/dev/git-repos/vault-bash-completion/tests/tests.bats" ...
 ✗ 'vault ' => commands
   (from function `fail' in file tests/tests.bats, line 10,
    in test file tests/tests.bats, line 17)
     `[[ "$output" =~ 'audit-disable audit-enable' ]] || fail "output was: \"$output\""' failed
   output was: "vault-bash-completion.sh: line 22: COMP_WORDS: bad array subscript"
 ✓ 'vault c' => commands
 ✓ 'vault p' => commands
 ✓ 'vault r' => commands
 ✓ 'vault read' => cubbyhole/ secret/ sys/
 ✓ 'vault read c' => cubbyhole/
 ✓ 'vault read s' => secret/ sys/
 ✓ 'vault list' => cubbyhole/ secret/ sys/
 ✓ 'vault list c' => cubbyhole/
 ✓ 'vault list s' => secret/ sys/
 ✓ 'vault list cubbyhole/' => cubbyhole/test

11 tests, 1 failure
```

This issue was fixed for me with e45f544. Is it working for you now too?

**Comment by iljaweis** [comment]
Yes, it now works for me. Thanks! Sorry, I could have pointed out that I am using the exact bash version you mentioned.

**Comment by msabramo** [comment]
No problem! I'm glad that it's working now!

**Pull request merged**
